# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'morgan-social' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for morgan-social
  pod 'Parse'
  pod 'Parse/UI'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'MaterialComponents/Snackbar'
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/TextFields+Theming'
  pod 'DateTools'
  target 'morgan-socialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'morgan-socialUITests' do
    # Pods for testing
  end

end
